### PR TITLE
1.12 update

### PR DESCRIPTION
**Pull request by dartasen**

### CODE REVIEW

**Comment by Spiikesan** [comment]
I hope that it will be merged soon to have the plugin working for 1.12...

**Comment by dartasen** [comment]
Send me a message if this error is still appearing, It appears that a called method by JSONAPI is missing in spigot 1.12
I'll check this out soon 👍

**Comment by Spiikesan** [comment]
These errors appears all the time.
The build failed when the commit has been merged :( (https://ci.alecgorge.com/job/JSONAPI/)
The errors are "package net.minecraft.server.v1_12_R1 does not exist" and "package org.bukkit.craftbukkit.v1_12_R1 does not exist"
Thanks for your involvement to get this plugin working for 1.12 !
(Sorry if my English is bad, I'm French)

**Comment by dartasen** [comment]
Je vais regarder pour le build moi même

**Comment by alecgorge** [comment]
Thanks for this pull request! It definitely had some issues though and wouldn't compile. I have submitted a fix and build 139 works for 1.11.2 and 1.12: https://ci.alecgorge.com/job/JSONAPI/139/

**Pull request merged**
